name: Improvement API CI/CD

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]
    paths-ignore:
      - '**/README.md'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.10.1]
        poetry-version: [1.1.12]
        redis-version: [6]

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: improvement_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout improvement-api repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies with Poetry
        run: poetry install
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Run pytest
        env:
          DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/improvement_test
          REDIS_URL: redis://127.0.0.1:6379
          TEST_DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/improvement_test
          TEST_REDIS_URL: redis://127.0.0.1:6379
          BACKEND_CORS_ORIGINS: ${{ secrets.TEST_BACKEND_CORS_ORIGINS }}
        run: poetry run pytest

  cd:
    name: Deploy to Heroku
    needs: ci
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && needs.ci.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
